In [3]:
import geopandas as gpd
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import matplotlib
import numpy as np
from pathlib import Path

# Stops

In [4]:
base_path = Path('/home/rico/Documents/courses/11.C35/gtfs_data_prep')
stops = gpd.read_file(base_path / 'original_data/mbta_stops.geojson')
stops = stops.drop(columns=['stop_desc', 'location_type', 'agency_name', 'platform_code'])
stops_with_buffer = gpd.read_file(base_path / 'original_data/mbta_stops_with_buffer.geojson')
stops_with_buffer = stops_with_buffer.drop(columns=['stop_desc', 'location_type', 'agency_name', 'platform_code'])

In [5]:
stops.to_csv(base_path / 'mbta_stops/mbta_stops.geojson')
stops_with_buffer.to_csv(base_path / 'mbta_stops_with_buffer/mbta_stops_with_buffer.geojson')

In [6]:
# This is to explore the dataset visually
# stops.explore()

In [7]:
stops.columns

Index(['stop_id', 'stop_code', 'stop_name', 'zone_id', 'stop_url',
       'parent_station', 'wheelchair_boarding', 'level_id', 'routes',
       'geometry'],
      dtype='object')

In [8]:
stops_with_buffer.columns

Index(['stop_id', 'stop_code', 'stop_name', 'zone_id', 'stop_url',
       'parent_station', 'wheelchair_boarding', 'level_id', 'routes',
       'geometry'],
      dtype='object')

In [12]:
stops.head()

,stop_id,stop_code,stop_name,zone_id,stop_url,parent_station,wheelchair_boarding,level_id,routes,geometry
0,1,1,Washington St opp Ruggles St,ExpressBus-Downtown,https://www.mbta.com/stops/1,None,1,None,"[ { ""route_id"": ""1"", ""agency_id"": ""1"", ""route_...",POINT (-71.08275 42.33096)
1,10,10,Theo Glynn Way @ Newmarket Sq,LocalBus,https://www.mbta.com/stops/10,None,1,None,"[ { ""route_id"": ""8"", ""agency_id"": ""1"", ""route_...",POINT (-71.06879 42.33056)
2,10000,10000,Tremont St opp Temple Pl,LocalBus,https://www.mbta.com/stops/10000,None,1,None,"[ { ""route_id"": ""15"", ""agency_id"": ""1"", ""route...",POINT (-71.06291 42.35569)
3,10003,10003,Albany St opp Randall St,LocalBus,https://www.mbta.com/stops/10003,None,1,None,"[ { ""route_id"": ""1"", ""agency_id"": ""1"", ""route_...",POINT (-71.07624 42.33159)
4,10005,10005,Albany St opp E Concord St,LocalBus,https://www.mbta.com/stops/10005,None,1,None,"[ { ""route_id"": ""8"", ""agency_id"": ""1"", ""route_...",POINT (-71.07128 42.33502)

In [13]:
collapsed_stops = stops.groupby(['stop_name', 'zone_id', 'stop_url']).first().reset_index().set_crs('EPSG:4326')

collapsed_stops_with_buffer = stops_with_buffer.groupby(['stop_name', 'zone_id', 'stop_url']).first().reset_index().set_crs('EPSG:4326')

In [14]:
len(stops) - len(collapsed_stops)

569

In [15]:
collapsed_stops.columns

Index(['stop_name', 'zone_id', 'stop_url', 'stop_id', 'stop_code',
       'parent_station', 'wheelchair_boarding', 'level_id', 'routes',
       'geometry'],
      dtype='object')

In [16]:
# non_rapid_transit = ['LocalBus', 'SLWaterfrontNonLogan', 'ExpressBus-Downtown',
# 'CF-zone-buzzards', 'Boat-Aquarium', 'Boat-Hingham',
# 'Boat-Hull', 'CF-zone-hyannis', 'Boat-Lewis', 'Boat-Logan',
# 'Boat-Long', 'Boat-Rowes', 'Boat-Fan']

# collapsed_stops[collapsed_stops['zone_id'].isin(['RapidTransit'])].explore()

In [18]:
collapsed_stops.to_file(base_path / 'mbta_stops/mbta_stops_collapsed.geojson')
collapsed_stops_with_buffer.to_file(base_path / 'mbta_stops/mbta_stops_with_buffer_collapsed.geojson')

In [21]:
collapsed_stops_with_buffer.head()

,stop_name,zone_id,stop_url,stop_id,stop_code,parent_station,wheelchair_boarding,level_id,routes,geometry
0,1 W Milton St opp Ernest Ave,LocalBus,https://www.mbta.com/stops/8328,8328,8328,None,1,None,"[ { ""route_id"": ""33"", ""agency_id"": ""1"", ""route...","POLYGON ((-71.13367 42.24071, -71.13385 42.242..."
1,10 Centennial Drive - Boston Children's @ Peabody,LocalBus,https://www.mbta.com/stops/14586,14586,14586,None,1,None,"[ { ""route_id"": ""436"", ""agency_id"": ""1"", ""rout...","POLYGON ((-70.94181 42.52604, -70.942 42.52746..."
2,10 Centennial Drive - West,LocalBus,https://www.mbta.com/stops/24586,24586,24586,None,1,None,"[ { ""route_id"": ""436"", ""agency_id"": ""1"", ""rout...","POLYGON ((-70.94483 42.52699, -70.94501 42.528..."
3,10 Oak Park Dr,LocalBus,https://www.mbta.com/stops/49798,49798,49798,None,1,None,"[ { ""route_id"": ""351"", ""agency_id"": ""1"", ""rout...","POLYGON ((-71.24058 42.51542, -71.24077 42.516..."
4,10 Sylvan St,LocalBus,https://www.mbta.com/stops/4561,4561,4561,None,1,None,"[ { ""route_id"": ""435"", ""agency_id"": ""1"", ""rout...","POLYGON ((-70.93562 42.54652, -70.93581 42.547..."

In [10]:
collapsed_stops.nunique()

stop_name              6289
zone_id                  27
stop_url               7019
stop_id                7087
stop_code              6907
parent_station          264
wheelchair_boarding       3
level_id                 32
routes                  706
geometry               7076
dtype: int64

In [11]:
collapsed_stops.wheelchair_boarding.unique()

array([1, 0, 2], dtype=int32)

In [12]:
collapsed_stops_with_buffer.nunique()

stop_name              6289
zone_id                  27
stop_url               7019
stop_id                7087
stop_code              6907
parent_station          264
wheelchair_boarding       3
level_id                 32
routes                  706
geometry               7076
dtype: int64

In [13]:
collapsed_stops_with_buffer.wheelchair_boarding.unique()

array([1, 0, 2], dtype=int32)

# Lines

In [9]:
lines = gpd.read_file(base_path / 'original_data/mbta_lines.geojson')
lines = lines.drop(columns=['route_text_color'])

In [10]:
lines.columns

Index(['agency_name', 'route_id', 'agency_id', 'route_short_name',
       'route_long_name', 'route_desc', 'route_type', 'route_url',
       'route_color', 'route_sort_order', 'network_id', 'geometry'],
      dtype='object')

In [11]:
# lines.explore(color=lines['route_color'])

In [12]:
lines.head(5)

,agency_name,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_sort_order,network_id,geometry
0,MBTA,Red,1,None,Red Line,Rapid Transit,1,https://www.mbta.com/schedules/Red,#DA291C,10010,rapid_transit,"MULTILINESTRING ((-71.13955 42.39619, -71.1420..."
1,MBTA,Mattapan,1,None,Mattapan Trolley,Rapid Transit,0,https://www.mbta.com/schedules/Mattapan,#DA291C,10011,m_rapid_transit,"MULTILINESTRING ((-71.06318 42.2839, -71.0633 ..."
2,MBTA,Orange,1,None,Orange Line,Rapid Transit,1,https://www.mbta.com/schedules/Orange,#ED8B00,10020,rapid_transit,"MULTILINESTRING ((-71.05911 42.36419, -71.0604..."
3,MBTA,Green-B,1,B,Green Line B,Rapid Transit,0,https://www.mbta.com/schedules/Green-B,#00843D,10032,rapid_transit,"MULTILINESTRING ((-71.16656 42.34002, -71.1668..."
4,MBTA,Green-C,1,C,Green Line C,Rapid Transit,0,https://www.mbta.com/schedules/Green-C,#00843D,10033,rapid_transit,"MULTILINESTRING ((-71.14844 42.33631, -71.1491..."

In [13]:
lines.nunique()

agency_name           2
route_id            351
agency_id             2
route_short_name    182
route_long_name     348
route_desc            9
route_type            5
route_url           176
route_color           9
route_sort_order    351
network_id           17
geometry            351
dtype: int64

In [14]:
lines.to_file(base_path / 'mbta_lines/mbta_lines.geojson')

In [15]:
dup_lines = lines[lines.route_long_name.isin(lines[lines.route_long_name.duplicated()].route_long_name)]
colors = [matplotlib.colors.rgb2hex(rgba) for rgba in cm.rainbow(np.linspace(0, 1, len(dup_lines)))]
dup_lines.explore(color=colors)

In [16]:
dup_lines = lines[lines.route_long_name.duplicated()]
colors = [matplotlib.colors.rgb2hex(rgba) for rgba in cm.rainbow(np.linspace(0, 1, len(dup_lines)))]
dup_lines.explore(color=colors)

In [17]:
lines_deduplicated = lines[~lines.route_long_name.duplicated()]

In [19]:
lines_deduplicated.to_file(base_path / 'mbta_lines/mbta_lines_deduplicated.geojson')

# Deduplicate the lines with buffer

In [20]:
lines_with_buffer = gpd.read_file(base_path / 'original_data/mbta_lines_with_buffer.geojson')
lines_with_buffer = lines_with_buffer.drop(columns=['route_text_color'])

In [25]:
lines_with_buffer.columns

Index(['agency_name', 'route_id', 'agency_id', 'route_short_name',
       'route_long_name', 'route_desc', 'route_type', 'route_url',
       'route_color', 'route_sort_order', 'network_id', 'geometry'],
      dtype='object')

In [32]:
lines_with_buffer.head(5)

,agency_name,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_sort_order,network_id,geometry
0,MBTA,Red,1,None,Red Line,Rapid Transit,1,https://www.mbta.com/schedules/Red,#DA291C,10010,rapid_transit,"POLYGON ((-71.14269 42.39614, -71.14267 42.396..."
1,MBTA,Mattapan,1,None,Mattapan Trolley,Rapid Transit,0,https://www.mbta.com/schedules/Mattapan,#DA291C,10011,m_rapid_transit,"POLYGON ((-71.0925 42.26776, -71.09258 42.2676..."
2,MBTA,Orange,1,None,Orange Line,Rapid Transit,1,https://www.mbta.com/schedules/Orange,#ED8B00,10020,rapid_transit,"POLYGON ((-71.10696 42.3103, -71.10628 42.3113..."
3,MBTA,Green-B,1,B,Green Line B,Rapid Transit,0,https://www.mbta.com/schedules/Green-B,#00843D,10032,rapid_transit,"POLYGON ((-71.16742 42.34012, -71.16742 42.340..."
4,MBTA,Green-C,1,C,Green Line C,Rapid Transit,0,https://www.mbta.com/schedules/Green-C,#00843D,10033,rapid_transit,"POLYGON ((-71.14913 42.3357, -71.14826 42.3358..."

In [27]:
lines_with_buffer.nunique()

agency_name           2
route_id            351
agency_id             2
route_short_name    182
route_long_name     348
route_desc            9
route_type            5
route_url           176
route_color           9
route_sort_order    351
network_id           17
geometry            351
dtype: int64

In [28]:
dup_lines_with_buffer = lines_with_buffer[lines_with_buffer.route_long_name.isin(lines_with_buffer[lines_with_buffer.route_long_name.duplicated()].route_long_name)]
colors = [matplotlib.colors.rgb2hex(rgba) for rgba in cm.rainbow(np.linspace(0, 1, len(dup_lines_with_buffer)))]
dup_lines_with_buffer.explore(color=colors)

In [29]:
lines_with_buffer_deduplicated = lines_with_buffer[~lines_with_buffer.route_long_name.duplicated()]

In [30]:
lines_with_buffer_deduplicated.to_file(base_path / 'mbta_lines_with_buffer/mbta_lines_with_buffer_deduplicated.geojson')